# Generated by Django 6.1 on 2026-08-21 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produtor', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('localidade', models.CharField(max_length=100, verbose_name='Localidade')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_solicitacao', models.DateField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('equipamento', models.CharField(choices=[('TRATOR', 'Trator'), ('RETROESCAVADEIRA', 'Retroescavadeira')], max_length=20, verbose_name='Equipamento')),
                ('tipo_servico', models.CharField(blank=True, choices=[('ARAR', 'Arar'), ('GRADEAR', 'Gradear'), ('SULCAR', 'Sulcar'), ('ENCANTEIRAR', 'Encanteirar')], max_length=20, null=True, verbose_name='Tipo de Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField(verbose_name='Data do Atendimento')),
                ('nome_operador', models.CharField(max_length=255, verbose_name='Nome do Tratorista/Operador')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas Trabalhadas')),
                ('horimetro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Marcação do Horímetro')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='gestao.solicitacao', verbose_name='Solicitação')),
            ],
        ),
    ]
