# Generated by Django 6.1 on 2026-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='horimetro',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Atendimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horimetro_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro Final'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horimetro_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro Inicial'),
        ),
    ]
