# Generated by Django 6.1 on 2026-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_atendimento_horimetro_atendimento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo_servico',
            field=models.CharField(blank=True, choices=[('Trator', [('TRATOR_ARAR', 'Arar'), ('TRATOR_GRADEAR', 'Gradear'), ('TRATOR_SULCAR', 'Sulcar'), ('TRATOR_ENCANTEIRAR', 'Encanteirar'), ('TRATOR_SILAGEM', 'Silagem'), ('TRATOR_ROCAR', 'Roçar'), ('TRATOR_OUTROS', 'Outros')]), ('Retroescavadeira', [('RETRO_LIMP_ACUDE', 'Limpeza de açude/lago'), ('RETRO_LIMP_BEBEDOURO', 'Limpeza de bebedouro'), ('RETRO_ABERT_ACUDE', 'Abertura de açude/lago'), ('RETRO_ABERT_BEBEDOURO', 'Abertura de bebedouro'), ('RETRO_RETIRADA_TERRA', 'Retirada de terra'), ('RETRO_ABERT_VALA', 'Abertura de vala'), ('RETRO_LIMP_VALA', 'Limpeza de vala'), ('RETRO_ENTERRAR_ANIMAL', 'Enterrar animal em óbito'), ('RETRO_ABERT_ESTRADA', 'Abertura de estrada dentro da propriedade'), ('RETRO_LIMP_ESTRADA', 'Limpeza de estrada dentro da propriedade'), ('RETRO_REALIZ_PLATO', 'Realização de platô'), ('RETRO_ABERT_TRINCHEIRA', 'Abertura de trincheira para silagem'), ('RETRO_REALOC_MANILHA', 'Realocamento ou posicionamento de manilha'), ('RETRO_OUTROS', 'Outros')])], max_length=50, null=True, verbose_name='Tipo de Serviço'),
        ),
    ]
